### ISSUE TITLE
Improve the Button-Look

### ISSUE THREAD

**Issue by tuc0w** [SantiMA10/devops-streamdeck#22]
I'd suggest to improve the Button-Look since it is hard to identify which pipeline has passed or failed if we only see the GitLab logo and the status.

Here's a small mockup I made, the left button would be the easiest solution which only adds a title, to quickly identify the status of each pipeline I'd suggest to also add red/green indication and also parse the status:
![gitlab_ci-cd](https://user-images.githubusercontent.com/843830/77899005-55d8bc80-727c-11ea-9e29-7971c8b37a2e.png)

**Comment by SantiMA10** [comment]
The StreamDeck, at least at this moment, have a few limitations:
- The action only can display one text, to help to identify projects I recommend you to customize the action image with the [Stream Deck Key Creator](https://www.elgato.com/en/gaming/keycreator)
- It is not possible to change the color of text, only font, size and position (top, center, bottom). 
- The action only can have two images, but I like the idea of having two images: success and failure.

**Comment by tuc0w** [comment]
Adding the option to use two images in case of fail/pass would be a great idea, this way the user could add a title and will still see the result :)

**Comment by SantiMA10** [comment]
@tuc0w Sorry for the delay, but other projects taken out all my free time, if you feel that you can work on any of the open issues, please feel free to assign this issue to you and send a PR with the code.

**Comment by SantiMA10** [comment]
I just send the update with multiple images for success and failed states

**Comment by tuc0w** [comment]
Sorry I wasn't able to get back to you before you did the coding, it looks great!
