### ISSUE TITLE
Error on retrieving status

### ISSUE THREAD

**Issue by Caroga** [SantiMA10/devops-streamdeck#24]
Hi there, I've installed your plugin and tried configuring it to query the pipeline status of my private project on **gitlab.com**.

I've registered an access token with the scope set to API. 
The path to my project is `gitlab.com/groupname/subgroupname/reponame`
So I've configured the user (username/token) and left the domain field empty to use the default gitlab.com domain.
I've added the shortcut, selected my account and added the repo `groupname/subgroup/reponame` and left the branch empty.
To clarify: my username is absent from the repo reference. It is however my group and repo.
After pushing the button it states `error` only.

Could you please help me configure this properly?

**Comment by SantiMA10** [comment]
It's a bug, should be solved with the 1.3.1 update, I will let you know when is available in the store

**Comment by Caroga** [comment]
Great, thank you for picking this up! After it has been accepted into the store, should I need to update anything or reinstall? I'm not aware of any auto-update feature in streamdeck.

**Comment by SantiMA10** [comment]
1.3.1 is available now! I'm not sure how the StreamDeck handles the update process 😅

Let me know if everything is working fine.

**Comment by Caroga** [comment]
I did not have to do a thing, the button is now showing Success. 
Thank you for tackling this so quick!
