### ISSUE TITLE
Vercel (formerly ZEIT) support

### ISSUE THREAD

**Issue by tobimori** [SantiMA10/devops-streamdeck#30]

**Comment by SantiMA10** [comment]
Vercel docs: https://vercel.com/docs/api#getting-started

**Comment by SantiMA10** [comment]
@tobimori can you check the current support for vercel? I'm not sure if I cover all the cases since I'm not a heavy user of vercel

**Comment by tobimori** [comment]
I'll check it out later today!

**Comment by tobimori** [comment]
Can confirm that it works for me!

**Comment by SantiMA10** [comment]
@tobimori thanks!
