### ISSUE TITLE
Open instructions in real browser and not In-Streamdeck

### ISSUE THREAD

**Issue by tobimori** [SantiMA10/devops-streamdeck#31]
![](https://user-images.githubusercontent.com/29142128/81339719-e93cb300-90ae-11ea-8d80-2771a0d8becd.png)

**Comment by SantiMA10** [comment]
@tobimori I'm not sure if that is possible, let me check the docs

**Comment by tobimori** [comment]
Your should be able to send the same payload as you do in the property inspector

**Comment by SantiMA10** [comment]
Done and publish!
