### ISSUE TITLE
Document development setup

### ISSUE THREAD

**Issue by tobimori** [SantiMA10/devops-streamdeck#36]
Hi.
I'm interested in your development setup for this plugin. 
Could you document it so it's easier to contribute?
I tried to create all kinds of symlinks but Elgato won't recognize it as a plugin.

**Comment by SantiMA10** [comment]
You're absolutely right 🤦

**Comment by SantiMA10** [comment]
@tobimori Let me know if with the newly added information in the README you're able to set up the project.

Anyway, I will try to simplify a bit the build process and also document it, this is only a first step. If you have concrete questions about the setup, feel free to ask.

**Comment by tobimori** [comment]
That's fine - apparently windows handles hard symlinks differently (or at least the Elgato software)
