### ISSUE TITLE
Request: Travis-CI support

### ISSUE THREAD

**Issue by dgw** [SantiMA10/devops-streamdeck#40]
Most of the projects I help maintain use Travis-CI to run tests. I really love the idea of putting CI statuses on a Stream Deck device, and was excited when I saw this plugin in the list.

Note: I have no TypeScript experience, but if no one else is interested in this feature and implementing it falls to me, maybe I can figure out enough to be dangerous by cloning one of the existing actions. 😅

**Comment by SantiMA10** [comment]
Hi @dgw!

I just submitted a new version with Travis CI support, hopefully, it will be live by Monday. (I will let you know)

If you can test the integration and let me know if everything is working, we can close this issue.

**Comment by SantiMA10** [comment]
@dgw the update is now available in the store!

**Comment by dgw** [comment]
Got my first Travis project set up, and it seems to be working! Thanks for shipping this so fast. 😸
