### ISSUE TITLE
Insufficient documentation

### ISSUE THREAD

**Issue by SturmB** [SantiMA10/devops-streamdeck#43]
I'd love to use this Stream Deck extension/plug-in, but I cannot figure out how to get it to work. The button just always says "[…]eeds conf[…]" even after linking my Github account and filling out the repo field.

Is it mac only? I am using Windows.

**Comment by SantiMA10** [comment]
I never tried it on Windows, but it doesn't have anything to prevent it from working on Windows.

Can you provide a bit more context? Is it a public repo or private repo? Is your repo or an org repo?

**Comment by SturmB** [comment]
Hey, thanks for replying, Santi.

So I did a little experimenting. It turns out that private repos will not work with this plugin unless you specifically give the personal access token the privilege to do so:
![image](https://user-images.githubusercontent.com/6216224/109521012-d69acc80-7a7a-11eb-966b-702ae73bb9a4.png)

Otherwise, it will cause the icon to display "error".

The plugin _does_ work on my personal repos, but any repos that belong to an organization, even if I am the owner of it, do not work; the icon will only show "not found":
![image](https://user-images.githubusercontent.com/6216224/109519015-d4d00980-7a78-11eb-99e9-a48fcaa239fd.png)

So I think two things should take place. One, the documentation ought to be updated to clarify what repos the plugin will/won't work with. And two, if at all possible, I'd like to plugin to work with organization repos. At least, so long as the user has sufficient privileges on that repo.

**Comment by SantiMA10** [comment]
Thanks for the feedback, I will update the documentation with the extra information you provide and start investigating why it's not working with organization repositories.

**Comment by SantiMA10** [comment]
Can you try the organization repo without setting any branch? Seems like the GitHub API always returns 0 when I call it for an organization repo and a branch, hopes this workaround works until I solve the issue.

**Comment by SturmB** [comment]
Interesting. 🤔 Yes, by leaving the 'branch' field blank, the plugin does seem to pick up the action in the organization's repo. 🎉 Thankfully, my projects are not currently complex enough to require specifying a branch, so I'm okay with this bug for now. 😅

Thank you so much for your help, SantiMA10! 🙏🏻

**Comment by danielo515** [comment]
I still think the plugin needs more documentation. It is not clear to me what it is supposed to be showing after I have everything configured. Also the icon always shows needs configuration unless I provide a name for it. Is it worth opening a new issue about this?
