### ISSUE TITLE
Use fine-grained personal access tokens on GitHub

### ISSUE THREAD

**Issue by DennisBecker** [SantiMA10/devops-streamdeck#69]
The classic personal access tokens have a higher risk if they get compromised / stolen compared to a fine-grained access token.

It would be nice if the README details which rights are needed so a fine-grained access toen can be used easily.

**Comment by DennisBecker** [comment]
Whoops, I was to fast scanning the README ... closed

**Comment by SantiMA10** [comment]
I can investigate, but if you know which are the fine-grained options that the plugin need, feel free to open a PR with the change or comment it here and I will apply it to the README.

**Comment by DennisBecker** [comment]
I have tried it but it did not work. As I cannot remove the GitHub account or update the token, I cannot test it. The fine-graned tokens also always expire after 30, 60 or 90 days or you set an expiration date.
