### ISSUE TITLE
Self-hosted GitLab

### ISSUE THREAD

**Issue by tuc0w** [SantiMA10/devops-streamdeck#7]
Please allow self-hosted GitLab servers (including http-only).

If you don't have the time you can assign this issue to me and I will do it within the next days :)

**Comment by SantiMA10** [comment]
Hi @tuc0w!

I just submitted a new version (v1.1.0) with this feature, let me know if it works properly to close the issue.

Also thanks for the request!

**Comment by tuc0w** [comment]
Hey @SantiMA10,
thank you for responding so fast! Do you have any idea how long it takes to get approved?

**Comment by SantiMA10** [comment]
I don't know, but I will let you know when the people from elgato notifies me that the new version is available in the store

**Comment by SantiMA10** [comment]
@tuc0w the new version is now live in the store. 🚀🚀

**Comment by tuc0w** [comment]
@SantiMA10 I just tested the new version but sadly it won't save the token, repo and branch (only the url gets saved) which results in displaying an error :(

I tried the whole api url with the same token in postman and it works:
```json
[
    {
        "id": 49,
        "sha": "b95c4ea882030f2484f52d764eeffc5ef740141c",
        "ref": "master",
        "status": "success",
        "created_at": "2020-03-20T10:38:20.374Z",
        "updated_at": "2020-03-20T10:41:53.383Z",
        "web_url": "http://xxx/xxx/xxx/pipelines/49"
    }
]
```

**Comment by SantiMA10** [comment]
@tuc0w I hope that tomorrow with new 1.3.0 all the problems with the setting should be solved, also that version contains support to shared accounts #12

**Comment by tuc0w** [comment]
@SantiMA10 that sounds great thank you for your time and work, I am looking forward to that version 😌

**Comment by SantiMA10** [comment]
@tuc0w the 1.3.0 is now live in the store, let me know if everything works now

**Comment by tuc0w** [comment]
It works! And I got another suggestion to improve it but that's gonna be another issue :)
