### ISSUE TITLE
Cannot remove GitHub account

### ISSUE THREAD

**Issue by DennisBecker** [SantiMA10/devops-streamdeck#70]
I have tried a fine-grained access token and now I cannot remove this account. Selecting the account, then clicking remove does not remove the account.

This is mandatory as new tokens, fine-grained or personal access tokens, must have an expire date.

**Comment by SantiMA10** [comment]
Can you provide more information about this? I cannot reproduce it

**Comment by DennisBecker** [comment]
I have a Stream Deck MK.2 connected to a Macbook Pro with M1 chip, installed the stream deck software, added your plugin and added my GitHub account but when I click to remove the account nothing happens.

**Comment by dartiss** [comment]
I have the same issue. I have a MBP with M1.

**Comment by dartiss** [comment]
If it helps to get to the bottom of this, if I add the Github account again it shows alongside the original. However, I can remove one of them. But not the other one - my assumption here is that it doesn't allow the final account to be removed, whatever it may be.
